version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "bump(bun)"
    commit-message:
      prefix: 'chore(bun.lock): '
    cooldown:
      default-days: 5
      semvar-major-days: 30
      semvar-minor-days: 7
      semvar-patch-days: 3

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      timezone: "Asia/Tokyo"
    labels:
      - dependabot
      - "bump(github-actions)"
    commit-message:
      prefix: 'chore(github-actions): '
    cooldown:
      default-days: 5
      semvar-major-days: 30
      semvar-minor-days: 7
      semvar-patch-days: 3
